"""
Phase 4: Citations.

Citations are NOT generated by the LLM -- they're built deterministically
from the retrieved chunk metadata that was attached back in Phase 1/2.
This guarantees citations can never be hallucinated: they're just "which
chunks were actually retrieved", surfaced in structured form.
"""
import re


def build_citations(chunks: list[dict]) -> list[dict]:
    """
    Args:
        chunks: the retrieved chunks used to build the prompt (same order
                as the [Source N] numbering in prompt_builder.build_prompt)

    Returns:
        [{"source_number", "filename", "page_number", "snippet"}, ...]
    """
    citations = []
    for i, chunk in enumerate(chunks):
        citations.append({
            "source_number": i + 1,
            "filename": chunk["filename"],
            "page_number": chunk["page_number"],
            "snippet": chunk["text"][:150].strip() + "...",
        })
    return citations


def extract_cited_source_numbers(answer_text: str) -> list[int]:
    """
    Parses which [Source N] tags the LLM actually referenced in its answer,
    so the UI can highlight only the citations actually used (vs. all
    retrieved chunks, some of which may not have been relevant).
    """
    matches = re.findall(r"\[Source (\d+)\]", answer_text)
    return sorted(set(int(m) for m in matches))
